version: '3'

services:
  example-checker:
    build: .
    # coordinate the exposed port with other service/checker authors to avoid overlap
    ports:
      - 7891:8000
    environment:
     - MONGO_ENABLED=1
     - MONGO_HOST=example-db
     - MONGO_PORT=27017
     - MONGO_USER=enoislove
     - MONGO_PASSWORD=enoislife
  example-db:
    image: mongo
    volumes:
      - ./db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: enoislove
      MONGO_INITDB_ROOT_PASSWORD: enoislife
